org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.233
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.21-nightly-SNAPSHOT
## Mod Properties
mod_id=wyrmroost
mod_name=Wyrmroost
mod_license=All Rights Reserved
mod_version=2.0.0-dev
mod_group_id=com.github.wolfshotz
mod_authors=WolfShotz, Kingdomall, Shannieann, Ukan, Nord_Act
mod_description=
